development:
  adapter: postgresql
  encoding: utf8
  database: shawsome_development
  pool: 5
  username: shawsome
  password: 


test: &TEST
  adapter: postgresql
  encoding: utf8
  database: shawsome_development
  pool: 5
  username: shawsome
  password: 

production:
  adapter: postgresql
  encoding: utf8
  database: shawsome_development
  pool: 5
  username: shawsome
  password: 


cucumber:
  <<: *TEST